apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: simple-udp-fleet
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        agones.dev/gameserver: simple-game-server
    spec:
      ports:
      - name: default
        portPolicy: Dynamic
        containerPort: 7654
        protocol: UDP
      template:
        spec:
          containers:
          - name: simple-game-server
            image: simple-game-server:0.1
            imagePullPolicy: Never
