// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/lobby.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_lobby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JoinResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	GameServerIp   string                 `protobuf:"bytes,2,opt,name=game_server_ip,json=gameServerIp,proto3" json:"game_server_ip,omitempty"`
	GameServerPort int32                  `protobuf:"varint,3,opt,name=game_server_port,json=gameServerPort,proto3" json:"game_server_port,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_proto_lobby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JoinResponse) GetGameServerIp() string {
	if x != nil {
		return x.GameServerIp
	}
	return ""
}

func (x *JoinResponse) GetGameServerPort() int32 {
	if x != nil {
		return x.GameServerPort
	}
	return 0
}

var File_proto_lobby_proto protoreflect.FileDescriptor

const file_proto_lobby_proto_rawDesc = "" +
	"\n" +
	"\x11proto/lobby.proto\x12\x05lobby\"&\n" +
	"\vJoinRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"v\n" +
	"\fJoinResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12$\n" +
	"\x0egame_server_ip\x18\x02 \x01(\tR\fgameServerIp\x12(\n" +
	"\x10game_server_port\x18\x03 \x01(\x05R\x0egameServerPort2H\n" +
	"\fLobbyService\x128\n" +
	"\tJoinMatch\x12\x12.lobby.JoinRequest\x1a\x13.lobby.JoinResponse\"\x000\x01B^\n" +
	"\tcom.lobbyB\n" +
	"LobbyProtoP\x01Z\x11go-learn/pb/proto\xa2\x02\x03LXX\xaa\x02\x05Lobby\xca\x02\x05Lobby\xe2\x02\x11Lobby\\GPBMetadata\xea\x02\x05Lobbyb\x06proto3"

var (
	file_proto_lobby_proto_rawDescOnce sync.Once
	file_proto_lobby_proto_rawDescData []byte
)

func file_proto_lobby_proto_rawDescGZIP() []byte {
	file_proto_lobby_proto_rawDescOnce.Do(func() {
		file_proto_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lobby_proto_rawDesc), len(file_proto_lobby_proto_rawDesc)))
	})
	return file_proto_lobby_proto_rawDescData
}

var file_proto_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_lobby_proto_goTypes = []any{
	(*JoinRequest)(nil),  // 0: lobby.JoinRequest
	(*JoinResponse)(nil), // 1: lobby.JoinResponse
}
var file_proto_lobby_proto_depIdxs = []int32{
	0, // 0: lobby.LobbyService.JoinMatch:input_type -> lobby.JoinRequest
	1, // 1: lobby.LobbyService.JoinMatch:output_type -> lobby.JoinResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_lobby_proto_init() }
func file_proto_lobby_proto_init() {
	if File_proto_lobby_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lobby_proto_rawDesc), len(file_proto_lobby_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lobby_proto_goTypes,
		DependencyIndexes: file_proto_lobby_proto_depIdxs,
		MessageInfos:      file_proto_lobby_proto_msgTypes,
	}.Build()
	File_proto_lobby_proto = out.File
	file_proto_lobby_proto_goTypes = nil
	file_proto_lobby_proto_depIdxs = nil
}
